lib/guard/guardfile/generator.rb
spec/lib/guard/guardfile/generator_spec.rb

This is similar to regular plugin loading, but stack traces aren't helpful here.

Print original errors while generating Guardfiles

---

lib/guard/notifier.rb

Notifier.notify previously had only one required parameter. This behavior is expected by plugins.
I encountered this error when using a guard-sprockets.

Backward compatibility fix of Notifier.notify signature

---

.gitignore
bin/_guard-core
bin/guard
guard.gemspec
lib/guard.rb
lib/guard/internals/scope.rb
lib/guard/templates/Guardfile

This uses the advertised solution but it integrates it into the gem.
`bin/guard` is now the wrapper and it and it the original guard is now
`bin/_guard-core`.
All parameters to the wrapper are passed down to `_guard-core` --> all
tests are green.
I think this is much better from the user's perspective.

Integrate the reload functionality

---

bin/guard

This allows guard to be run using only RubyGems

Allow Guard to work without a Gemfile

---

bin/guard

ignore_interrupts broke autoreloads because it didn't return the same
way `system` did (return $? == 0).
Basically:
When I start Guard
And run `touch Guardfile`
I expect a reload rather then an exit.
Don't know how to make proper feature spec out of this because of since this should start two _guard-core instances.

Fix ignore_interrupts so that it doesn't break autoreloads

---

features/init.feature
lib/guard/cli/environments/valid.rb
lib/guard/dsl_reader.rb
lib/guard/plugin_util.rb
spec/lib/guard/cli/environments/valid_spec.rb
spec/lib/guard/dsl_reader_spec.rb
spec/lib/guard/plugin_util_spec.rb

- allow `guard init` to add plugins to empty Guardfile
- fix parameters in DslReader to handle cases when Guardfile uses notification
(Fixes #765)

Fixes Guardfile handling edge cases [fix 765]

---

README.md

@thibaudgg , @rymai - I wanted to change the maintainer CTA notice a bit.
I don't want people to get the impression the project is abandoned (which is far from true) - and by doing so guard is less likely to find active maintainers or even contributors.
(The notice gives the impression the project is dead and that there are bugs with no one to fix them).
Ideas for better message would be great (same probably goes for the Listen project).

Modified the info about maintainers

---

Gemfile
features/init.feature
features/step_definitions/guard_steps.rb
lib/guard/internals/debugging.rb
spec/lib/guard/internals/debugging_spec.rb

Spawn() is used by Guard::RSpec

also trace spawn() calls when debugging

---

lib/guard/cli/environments/valid.rb
lib/guard/guardfile/generator.rb
spec/lib/guard/cli/environments/valid_spec.rb
spec/lib/guard/guardfile/generator_spec.rb

i.e. running 'bundle exec guard init rspec' with guard-rspec not
available will exit with the 1 exit code.
@e2 Is it an acceptable solution?

Fix #771, Guard now fails with the 1 exit code when plugin is not available

---

lib/guard/commander.rb
spec/lib/guard/commander_spec.rb

- state is now properly described
- describe pause in a less misleading way

Fix misleading pause message

---

lib/guard/watcher.rb
lib/guard/watcher/pattern.rb
lib/guard/watcher/pattern/deprecated_regexp.rb
lib/guard/watcher/pattern/match_result.rb
lib/guard/watcher/pattern/matcher.rb
lib/guard/watcher/pattern/pathname_path.rb
lib/guard/watcher/pattern/simple_path.rb
spec/lib/guard/watcher/pattern/deprecated_regexp_spec.rb
spec/lib/guard/watcher/pattern/match_result_spec.rb
spec/lib/guard/watcher/pattern/matcher_spec.rb
spec/lib/guard/watcher/pattern/pathname_path_spec.rb
spec/lib/guard/watcher/pattern/simple_path_spec.rb
spec/lib/guard/watcher/pattern_spec.rb
spec/lib/guard/watcher_spec.rb

improvements:
- allow regexp group names like /(?<base>.*).rb/
- allows custom matcher objects passed to watch()
- better/smarter handling of Pathnames (for future)
development:
- split matching into files by pattern type
- organized test cases by pattern type
- correct misleading param name

rework watch matching + allow regexp named groups

---

features/step_definitions/guard_steps.rb
spec/lib/guard/cli_spec.rb

Fix Travis build on JRuby by avoiding missing JRuby feature
(killing Pry instance fails due to since input stream can't be interrupted)

disable Pry kill spec failing on JRuby

---

lib/guard/runner.rb
lib/guard/ui.rb
spec/lib/guard/ui_spec.rb

Closes #849.
Does two things: 
1. Fixes `calling_plugin_name`. This implementation lazily scans the callstack, by default to the depth I discovered guard plugins normally appeared (6), and returns when it finds a value. This fixes some undocumented filtering issues where no filter would apply because the prior implementation only tried to match whatever the third item in the call stack happened to be, which for implementation reasons must always be `"Guard::UI"`.
It updates the regex with a negative lookbehind to make sure it isn't inside a Guard library file. 
Since it still sometimes matches the guard gem's entrypoint (`guard/lib/guard.rb`), that result is also discarded.
2. Moves log tagging off of relying on `calling_plugin_name` entirely and uses more reliable builtin `Lumberjack` …

Correctly sets up progname in logger.

---

.travis.yml
spec/spec_helper.rb

This should allow us to get rid of:
```
W, [2016-12-30T22:35:32.715873 #4325]  WARN -- :       This usage of the Code Climate Test Reporter is now deprecated. Since version
1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
run the provided `codeclimate-test-reporter` binary separately to report your
results to Code Climate.
More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md
```

Execute the codeclimate-test-reporter bin as a separate CI step

---

lib/guard/cli.rb

Fix default type on listen_to method_option for newer versions of Thor

---

lib/guard/terminal.rb
spec/lib/guard/terminal_spec.rb

Fixes #858
Tested on OSX (macOS Sierra 10.12) and Ubuntu 12.04.5 LTS

Fixes 858 - guard -c does not clear window buffer on OSX

---

README.md

I think it's great to avoid typing `bundle exec <command>` having it aliased as `be <command>`

Add aliasing section inside tired-of-typing bundle exec 

---

README.md

This PR changes the build badge to show the status of `master` instead of the status of _all_ branches.

README: Build badge shows master branch status

---

.travis.yml

This PR updates the build matrix in Travis to:
- use `jruby-9.1.13.0`, latest release
- use `JRUBY_OPTS=--debug` to report coverage numbers
- place jruby-9.1.13.0 outside of `allowed_failures`
- use `rbx-2` - **Update**: [rbx-2 is the name, but it fails to install its deps](https://travis-ci.org/guard/guard/jobs/284112500)
- (Style change) order the settings in the YAML file.
I'll back out of any change if you folks don't like it.

Travis: update CI matrix to include latest release of JRuby

---

bin/guard

This is a proposed fix for https://github.com/guard/guard/issues/878. Mind you, I didn't run the specs (:innocent:) nor did I test it under Windows, but as I understand the code the wrong behavior would've also happened under Windows.

Run core with same Ruby version as it was started with.

---

guard.gemspec

https://github.com/guard/guard/issues/863

fix lumberjack version runtime dependency

---

CONTRIBUTING.md

There is some good documentation in the wiki which helps (plugin) developers, so make it a bit easier to find.

CONTRIBUTING.md: add links to the wiki

---

features/logging.feature
lib/guard/dsl.rb
spec/lib/guard/dsl_spec.rb

The Guard::Dsl#logger method is ignoring the user provided options. This branch fixes that, so that [the instructions provided in the Guard wiki](https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#logger) are accurate again.
The fix is just a single line change but I wanted to add some tests to make sure it's working properly.
See also #852.
PS: Credits to @christhekeele for pointing out the source of the problem in #852.

Fix: Correctly set logger options from Guardfile

---

spec/lib/guard/dsl_describer_spec.rb

While testing with rspec, I found following warning:
~~~
$ rspec -rspec_helper spec
Run options: include {:focus=>true}
All examples were filtered out; ignoring {:focus=>true}
Randomized with seed 24497
................................................................*......................................................................................*................................................................................................................................................................................................................................................................................................................WARNING: `allow(...).to receive(..).ordered` is not supported and will have no effect, use `and_return(*ordered_values)` instead.. Called …

Fix rspec warning message.

---

spec/lib/guard/plugin_util_spec.rb

While testing with rspec, I found following errors:
~~~
$ rspec -rspec_helper --seed 50224
Run options: include {:focus=>true}
All examples were filtered out; ignoring {:focus=>true}
Randomized with seed 50224
...............................................WARNING: `allow(...).to receive(..).ordered` is not supported and will have no effect, use `and_return(*ordered_values)` instead.. Called from /builddir/build/BUILD/guard-2.14.2/usr/share/gems/gems/guard-2.14.2/spec/lib/guard/dsl_describer_spec.rb:141:in `block (3 levels) in <top (required)>'.
WARNING: `allow(...).to receive(..).ordered` is not supported and will have no effect, use `and_return(*ordered_values)` instead.. Called from /builddir/build/BUILD/guard-2.14.2/usr/share/gems/gems/guard-2.14.2/spec/lib/guard/dsl_describer_spec.rb: …

Fix rspec random test failure.

---

lib/guard/watcher.rb
lib/guard/watcher/pattern/matcher.rb
spec/lib/guard/watcher/pattern/matcher_spec.rb
spec/lib/guard/watcher_spec.rb

(and `Guard::Watcher::Pattern::Matcher`)
Simplify the testing `Guard::Plugin` with `Guard::Watcher` default options.

Add `#==` method for `Guard::Watcher`

---

lib/guard/plugin_util.rb
spec/lib/guard/plugin_util_spec.rb

(proposal) If you prefer to use a module for your plugin, this will break, and it's annoying to work around.

Improve type checking

---

lib/guard/dsl.rb
lib/guard/runner.rb

This PR fixes YARD warnings.
- Avoid warnings like: `[UnknownParam] @param tag has unknown parameter name: options`

Fix YARD annotation

---

lib/guard/guardfile/evaluator.rb
lib/guard/guardfile/generator.rb
spec/lib/guard/guardfile/evaluator_spec.rb
spec/lib/guard/guardfile/generator_spec.rb
spec/spec_helper.rb

Reopening of https://github.com/guard/guard/pull/923.
Ruby 2.6 quietly changed `Pathname#read` from using `IO.read` to `File.read`, therefore approximately 6 tests fail with "stub me!" errors.
This fixes the problem by stubbing Pathname and some of its methods instead of stubbing underlying methods used by `Pathname#read` internally.
Relevant Ruby commit: ruby/ruby@53a5b27

 Stub Pathname instead of IO.read in spec

---

lib/guard/commander.rb
lib/guard/notifier.rb
spec/lib/guard/commander_spec.rb

Problem
===
When guard raises an error, it does not clean up itself.
`Guard::Commander#stop` method is called only if the process stops successfully or it receives a signal.
So it is not called if guard raises an unexpected error.
Solution
===
Call `stop` method always.
The real problem in my case
=== 
I use [guard-process](https://github.com/guard/guard-process).
It executes a process, and kill the process via `stop` method. So if `stop` method is not called, the process will be a zombie. 
Guard raises an error and exits without calling `stop` method if the watched directory contains an unpermitted directory. 
Reproducing process:
```ruby
guard 'process', :command => 'sleep 1m' do
watch(%r!foo/.+!)
end
```
```console
$ mkdir -p foo/bar
$ chmod 700 foo/bar
$ sudo chown root:root foo/bar
$ …
```

Cleanup guard process anytime

---

spec/spec_helper.rb

it seems like there is no point to cover spec folder

add simplecov filter for a spec folder

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.8.0**.
[JRuby 9.2.8.0 release blog post](https://www.jruby.org/2019/08/12/jruby-9-2-8-0.html)
- The use of openjdk8 allows us to wait with all the --allow-opens needed to run with a newer JDK

CI: Use jruby-9.2.8.0 and pick openjdk8

---

.github/release-drafter.yml
.github/workflows/push.yml
CONTRIBUTING.md
README.md

Similarly to https://github.com/guard/listen/pull/466.
This commit sets up a GitHub Actions workflow that uses Release Drafter to automatically maintain release notes on every push.
In practice this means that contributors no longer have to manually update the CHANGELOG, which is something that is easy to forget and often introduces tedious merge conflicts.
Instead, Release Drafter automatically adds the title of the PR to the GitHub release notes to a draft release, crediting the author of the PR, and linking to the PR number. Release Drafter furthermore organizes the release notes into sections according to the labels assigned to the PRs:
- ⚠️ Breaking
- 🐛 Bug Fix
- 📚 Docs
- ✨ Feature
- 🏠 Housekeeping
This also simplifies the release process for maintainers: instead of manually updating …

Maintain release notes using GitHub Actions

---

.rubocop.yml
lib/guard/commander.rb
spec/lib/guard/commander_spec.rb

This should fix https://github.com/guard/guard/issues/937.

Don't swallow evaluator error by handling non-existant listener & interactor

---

README.md

This PR removes the link to Google+ community page from README.md.
As explained in <https://plus.google.com/communities/110022199336250745477>, Google+ has been closed in April 2019 and we cannot read the community page any longer.

Remove the link to Google+ community page

---

lib/guard/jobs/pry_wrapper.rb
spec/lib/guard/jobs/pry_wrapper_spec.rb

Fix support for Pry 0.13

---

lib/guard/version.rb

This version will include the fix for Pry > 0.13 (https://github.com/guard/guard/pull/958).

Bump VERSION to 2.16.2

---

lib/guard/jobs/pry_wrapper.rb

The XDG Base Directory Specification (which is currently used by
FOSS projects such as Git, Tmux, Pry, Rspec) provides a default
location for various file formats, including config/rc/history files.
This comment refactors pry_wrapper.rb to load GUARD_RC and
HISTORY_FILE from XDG_CONFIG_HOME and XDG_DATA_HOME
respectively if they are both set and the corresponding files exist
within the guard subdirectory within the XDG locations.
To maintain backwards compatibility it defaults back to ~/.guardrc
and ~/.guard_history if the respective XDG environment variable does
not exist or there is no corresponding file.

Refactor pry_wrapper.rb to be XDG compliant

---

lib/guard/version.rb

- Refactor pry_wrapper.rb to be XDG compliant (#962)
- Add Ruby 2.7.3 and 3.0.1 to the test matrix (#969)
- Bring compatibility with Ruby 3 explicit keyword arguments (#969)

Bump VERSION to 2.17.0

---

.travis.yml

This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known

CI: Update build matrix patch versions

---

guard.gemspec

Trying to bump the required `pry` version so people can bump their `pry-byebug` version to remove this warning. ([fixed](https://github.com/deivid-rodriguez/pry-byebug/blob/bf28c9781c434b2f00a83130ec5a8a992a691183/lib/pry-byebug/control_d_handler.rb#L1-L9))

pry 0.13.0

---

guard.gemspec

Since DocumentUp is down and the `guardgem.org` domain hasn't been renewed, let's go back to plain old GitHub pages.
Fixes https://github.com/guard/guard/issues/977.

Update URL of the project homepage

---

lib/guard/dsl_describer.rb

This library will no longer be shipped with Ruby 3.5.0, and will emit a warning.
In the source code, this was unused.

Drop unused require ostruct to avoid a Ruby warning,

---

guard.gemspec

By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/guard which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/#metadata

Provide a 'Changelog' link on rubygems.org/gems/guard

---

guard.gemspec

When running guard 2.19.0 under Ruby 3.4.0rc1, Ruby prints warnings about upcoming incompatibility:
```
$ guard
~/dev/gems/guard/lib/guard.rb:2: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
~/dev/gems/guard/bin/_guard-core:11: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
23:57:58 - INFO - Guard::RSpec is running
23:57:58 - INFO - Guard is now watching at '...'
```
When `logger` and `ostruct` gems are explicitly added as dependencies in the `guard.gemspec`, the warnings are no longer …

Get rid of compatibility warnings under Ruby 3.4.
